[pytest]
testpaths = tests
python_files = test_*.py
norecursedirs =
    .git
    .pytest_cache
    __pycache__
    alembic
    bin
    greenlet
    include
    mako
    markupsafe
    sqlalchemy
    *-*.dist-info
