"""add notification_dryruns, inbox_messages, event_logs

Revision ID: 93cae4c4096e
Revises: ed399767f3c3
Create Date: 2026-06-16 12:04:37.570760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93cae4c4096e'
down_revision: Union[str, None] = 'ed399767f3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=True),
    sa.Column('props', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_user_id'), ['user_id'], unique=False)

    op.create_table('inbox_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbox_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbox_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbox_messages_user_id'), ['user_id'], unique=False)

    op.create_table('notification_dryruns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_dryruns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_dryruns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_dryruns_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_dryruns_template'), ['template'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_dryruns_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_dryruns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_dryruns_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_dryruns_template'))
        batch_op.drop_index(batch_op.f('ix_notification_dryruns_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_notification_dryruns_id'))

    op.drop_table('notification_dryruns')
    with op.batch_alter_table('inbox_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbox_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_inbox_messages_id'))
        batch_op.drop_index(batch_op.f('ix_inbox_messages_created_at'))

    op.drop_table('inbox_messages')
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_logs_id'))
        batch_op.drop_index(batch_op.f('ix_event_logs_event'))
        batch_op.drop_index(batch_op.f('ix_event_logs_created_at'))

    op.drop_table('event_logs')
    # ### end Alembic commands ###
