"""add gamification models (daily_checkin, user_streak, weekly_score)

Revision ID: 9ec3a2a83127
Revises: dbeba0aeb1e6
Create Date: 2026-06-16 10:28:30.377121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ec3a2a83127'
down_revision: Union[str, None] = 'dbeba0aeb1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date_checkin')
    )
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checkins_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_checkins_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_checkins_user_id'), ['user_id'], unique=False)

    op.create_table('user_streaks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('max_streak', sa.Integer(), nullable=True),
    sa.Column('last_checkin_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('weekly_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'class_id', 'week_start', name='uq_user_class_week')
    )
    with op.batch_alter_table('weekly_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_scores_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_scores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_scores_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_scores_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_scores_week_start'))
        batch_op.drop_index(batch_op.f('ix_weekly_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_scores_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_scores_class_id'))

    op.drop_table('weekly_scores')
    op.drop_table('user_streaks')
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_checkins_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_checkins_id'))
        batch_op.drop_index(batch_op.f('ix_daily_checkins_date'))

    op.drop_table('daily_checkins')
    # ### end Alembic commands ###
