"""add question_comments table

Revision ID: c0831c8d3cf9
Revises: 93cae4c4096e
Create Date: 2026-06-16 12:32:41.450438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c0831c8d3cf9'
down_revision: Union[str, None] = '93cae4c4096e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_comments', schema=None) as batch_op:
        batch_op.create_index('idx_student_question', ['student_id', 'question_id'], unique=False)
        batch_op.create_index('idx_teacher_assignment', ['teacher_id', 'assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_comments_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_comments_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_comments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_comments_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_comments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_question_comments_student_id'))
        batch_op.drop_index(batch_op.f('ix_question_comments_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_comments_id'))
        batch_op.drop_index(batch_op.f('ix_question_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_question_comments_assignment_id'))
        batch_op.drop_index('idx_teacher_assignment')
        batch_op.drop_index('idx_student_question')

    op.drop_table('question_comments')
    # ### end Alembic commands ###
